import asyncio
from typing import Protocol


class SearchProjectionClient(Protocol):
    async def run(self, *, stop: asyncio.Event) -> None: ...

    async def process_one(self) -> bool: ...

    async def assert_visibility_ready(self) -> None: ...

    async def reindex_all(self, *, page_size: int = 500) -> int: ...
