from typing import Any, Protocol


class NewsLifecycleStorage(Protocol):
    async def get(self, session: Any, news_id: Any, *, lock: bool = False) -> Any: ...

    async def edit(self, session: Any, news: Any, changes: dict[str, Any], actor: str) -> Any: ...

    async def transition(self, session: Any, news: Any, target: Any, actor: str) -> None: ...

    async def reprocess(self, session: Any, news: Any, actor: str) -> Any: ...
