from typing import Any, Protocol


class NewsAdminStorage(Protocol):
    async def stats(self) -> dict[str, Any]: ...

    async def news(self, news_id: Any) -> dict[str, Any]: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...
